CREATE TABLE dbo.PCF00200 (
	OPTPOSIT SMALLINT(5),
	OPTCODE CHAR(101),
	ANSWRKEY SMALLINT(5),
	OPTION_DESCRIPTION CHAR(61),
	ANSWRCD CHAR(15),
	ANSWRABB CHAR(31),
	LISTPRCE NUMERIC(19,5),
	OPTMULTIP NUMERIC(19,5),
	INACTIVE TINYINT(3),
	DEX_ROW_ID INT(10)
);
