
    
    {% snapshot DIM_CUSTOMER_SNAPSHOT_STEP1 %}

    {{
        config(
        target_schema='EDW_STAGING_SNAPSHOT',
        unique_key='UNIQUE_ID_KEY',
        strategy='check',
        check_cols=['CUSTOMER_NAME', 'FIRST_NAME', 'MIDDLE_NAME', 'LAST_NAME', 'SUFFIX_NAME', 'DOCUMENT_BLOCK_IND', 'PHYSICAL_ADDRESS_LINE_1', 'PHYSICAL_ADDRESS_LINE_2', 'PHYSICAL_ADDRESS_CITY_NAME', 'PHYSICAL_ADDRESS_STATE_CODE', 'PHYSICAL_ADDRESS_STATE_NAME', 'PHYSICAL_ADDRESS_POSTAL_CODE', 'PHYSICAL_ADDRESS_COUNTY_NAME', 'PHYSICAL_ADDRESS_COUNTRY_NAME', 'PHYSICAL_ADDRESS_VALIDATED_IND', 'PHYSICAL_ADDRESS_COMMENT_TEXT', 'PHYSICAL_FORMATTED_ADDRESS_POSTAL_CODE', 'PHYSICAL_FORMATTED_ADDRESS_ZIP_CODE', 'PHYSICAL_FORMATTED_ADDRESS_ZIP4_CODE', 'MAILING_STREET_ADDRESS_1', 'MAILING_STREET_ADDRESS_2', 'MAILING_ADDRESS_CITY_NAME', 'MAILING_ADDRESS_STATE_CODE', 'MAILING_ADDRESS_STATE_NAME', 'MAILING_ADDRESS_POSTAL_CODE', 'MAILING_ADDRESS_COUNTY_NAME', 'MAILING_ADDRESS_COUNTRY_NAME', 'MAILING_FORMATTED_ADDRESS_POSTAL_CODE', 'MAILING_FORMATTED_ADDRESS_ZIP_CODE', 'MAILING_FORMATTED_ADDRESS_ZIP4_CODE', 'MAILING_ADDRESS_VALIDATED_IND', 'MAILING_ADDRESS_COMMENT_TEXT'],
        )
    }}

    select CUSTOMER_NAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX_NAME, DOCUMENT_BLOCK_IND, PHYSICAL_ADDRESS_LINE_1, PHYSICAL_ADDRESS_LINE_2, PHYSICAL_ADDRESS_CITY_NAME, PHYSICAL_ADDRESS_STATE_CODE, PHYSICAL_ADDRESS_STATE_NAME, PHYSICAL_ADDRESS_POSTAL_CODE, PHYSICAL_ADDRESS_COUNTY_NAME, PHYSICAL_ADDRESS_COUNTRY_NAME, PHYSICAL_ADDRESS_VALIDATED_IND, PHYSICAL_ADDRESS_COMMENT_TEXT, PHYSICAL_FORMATTED_ADDRESS_POSTAL_CODE, PHYSICAL_FORMATTED_ADDRESS_ZIP_CODE, PHYSICAL_FORMATTED_ADDRESS_ZIP4_CODE, MAILING_STREET_ADDRESS_1, MAILING_STREET_ADDRESS_2, MAILING_ADDRESS_CITY_NAME, MAILING_ADDRESS_STATE_CODE, MAILING_ADDRESS_STATE_NAME, MAILING_ADDRESS_POSTAL_CODE, MAILING_ADDRESS_COUNTY_NAME, MAILING_ADDRESS_COUNTRY_NAME, MAILING_FORMATTED_ADDRESS_POSTAL_CODE, MAILING_FORMATTED_ADDRESS_ZIP_CODE, MAILING_FORMATTED_ADDRESS_ZIP4_CODE, MAILING_ADDRESS_VALIDATED_IND, MAILING_ADDRESS_COMMENT_TEXT, UNIQUE_ID_KEY 
        from  {{ref('DSV_CUSTOMER') }}

    {% endsnapshot %}
    