
 ----SRC LAYER----
WITH
SCD1 as ( SELECT FILING_SOURCE_DESC, FILING_MEDIA_DESC, FIREFIGHTER_CANCER_IND, COMBINED_IND, SB223_IND, EMPLOYER_PREMISES_IND, EMPLOYER_PAID_PROGRAM_ENROLLMENT_DESC, EMPLOYER_PAID_PROGRAM_TYPE, EMPLOYER_PAID_PROGRAM_REASON ,     
	--, '1901-01-01' as DBT_VALID_FROM, '2099-12-31' as DBT_VALID_TO
	from      {{ ref( 'DSV_CLAIM_ELEMENT') }} ),
SCD2 as ( SELECT *    
	FROM      {{ ref('DIM_CLAIM_ELEMENT_SNAPSHOT_STEP1') }} ),
FINAL as ( SELECT * 
            FROM  SCD2 
                INNER JOIN SCD1 USING(  )  )
select * from FINAL