
 ----SRC LAYER----
WITH
SCD1 as ( SELECT CLAIM_DETAIL_HKEY, FILING_SOURCE_DESC, FILING_MEDIA_DESC, NATURE_OF_INJURY_CATEGORY, NATURE_OF_INJURY_TYPE, FIREFIGHTER_CANCER_IND, COVID_EXPOSURE_IND, COVID_EMERGENCY_WORKER_IND, COVID_HEALTH_CARE_WORKER_IND, COMBINED_IND, SB223_IND, EMPLOYER_PREMISES_IND, CATASTROPHIC_IND, EMPLOYER_PAID_PROGRAM_ENROLLMENT_DESC, EMPLOYER_PAID_PROGRAM_TYPE, EMPLOYER_PAID_PROGRAM_REASON, FILING_SOURCE_DESC, FILING_MEDIA_DESC, NATURE_OF_INJURY_CATEGORY, NATURE_OF_INJURY_TYPE, FIREFIGHTER_CANCER_IND, COVID_EXPOSURE_IND, COVID_EMERGENCY_WORKER_IND, COVID_HEALTH_CARE_WORKER_IND, COMBINED_IND, SB223_IND, EMPLOYER_PREMISES_IND, CATASTROPHIC_IND, EMPLOYER_PAID_PROGRAM_ENROLLMENT_DESC, EMPLOYER_PAID_PROGRAM_TYPE, EMPLOYER_PAID_PROGRAM_REASON , UNIQUE_ID_KEY    
	--, '1901-01-01' as DBT_VALID_FROM, '2099-12-31' as DBT_VALID_TO
	from      {{ ref( 'DSV_CLAIM_DETAIL') }} ),
SCD2 as ( SELECT *    
	FROM      {{ ref('DIM_CLAIM_DETAIL_SNAPSHOT_STEP1') }} ),
FINAL as ( SELECT * 
            FROM  SCD2 
                INNER JOIN SCD1 USING( UNIQUE_ID_KEY )  )
select * from FINAL