{{ config( 
materialized = 'view' 
) }}

---- SRC LAYER ----
WITH

SRC_CES            as ( SELECT *     FROM     {{ ref( 'DST_CLAIM_EXAM_SCHEDULE' ) }} ),

/*
SRC_CES            as ( SELECT *     FROM     STAGING.DST_CLAIM_EXAM_SCHEDULE ),

*/

---- LOGIC LAYER ----


, LOGIC_CES as ( 
	SELECT 	  
		 SCHEDULE_NUMBER                                    as                                    SCHEDULE_NUMBER	, 
		 CASE_ID                                            as                                            CASE_ID	, 
		 CASE_NO                                            as                                            CASE_NO	, 
		 CLM_NO                                             as                                             CLM_NO	, 
		 CLM_AGRE_ID                                        as                                        CLM_AGRE_ID	, 
		 CASE_OWNER                                         as                                         CASE_OWNER	, 
		 CASE_OWNER_LGN_NM                                  as                                  CASE_OWNER_LGN_NM	, 
		 CASE_OWNER_FUNCTIONAL_ROLE                         as                         CASE_OWNER_FUNCTIONAL_ROLE	, 
		 CASE_NM                                            as                                            CASE_NM	, 
		 CASE_INITIATED_DATE                                as                                CASE_INITIATED_DATE	, 
		 CASE_EFFECTIVE_DATE                                as                                CASE_EFFECTIVE_DATE	, 
		 CASE_DUE_DATE                                      as                                      CASE_DUE_DATE	, 
		 CASE_TYP_CD                                        as                                        CASE_TYP_CD	, 
		 CASE_TYP_NM                                        as                                        CASE_TYP_NM	, 
		 CASE_CTG_TYP_CD                                    as                                    CASE_CTG_TYP_CD	, 
		 CASE_CTG_TYP_NM                                    as                                    CASE_CTG_TYP_NM	, 
		 APP_CNTX_TYP_CD                                    as                                    APP_CNTX_TYP_CD	, 
		 APP_CNTX_TYP_NM                                    as                                    APP_CNTX_TYP_NM	, 
		 CASE_PRTY_TYP_CD                                   as                                   CASE_PRTY_TYP_CD	, 
		 CASE_PRTY_TYP_NM                                   as                                   CASE_PRTY_TYP_NM	, 
		 CASE_RSOL_TYP_CD                                   as                                   CASE_RSOL_TYP_CD	, 
		 CASE_RSOL_TYP_NM                                   as                                   CASE_RSOL_TYP_NM	, 
		 EXAM_TYPE_CD                                       as                                       EXAM_TYPE_CD	, 
		 EXAM_TYPE_DESC                                     as                                     EXAM_TYPE_DESC	, 
		 CASE_PRFL_CTG_TYP_CD                               as                               CASE_PRFL_CTG_TYP_CD	, 
		 CASE_PRFL_CTG_TYP_NM                               as                               CASE_PRFL_CTG_TYP_NM	, 
		 CASE_STT_TYP_CD                                    as                                    CASE_STT_TYP_CD	, 
		 CASE_STT_TYP_NM                                    as                                    CASE_STT_TYP_NM	, 
		 CASE_STS_TYP_CD                                    as                                    CASE_STS_TYP_CD	, 
		 CASE_STS_TYP_NM                                    as                                    CASE_STS_TYP_NM	, 
		 CASE_STS_RSN_TYP_CD                                as                                CASE_STS_RSN_TYP_CD	, 
		 CASE_STS_RSN_TYP_NM                                as                                CASE_STS_RSN_TYP_NM	, 
		 EXAM_REQUESTOR_TYP_CD                              as                              EXAM_REQUESTOR_TYP_CD	, 
		 EXAM_REQUESTOR_TYP_DESC                            as                            EXAM_REQUESTOR_TYP_DESC	, 
		 RQSTD_PHYSC_SPCLT_TYP_CODE                         as                         RQSTD_PHYSC_SPCLT_TYP_CODE	, 
		 RQSTD_PHYSC_SPCLT_TYP_DESC                         as                         RQSTD_PHYSC_SPCLT_TYP_DESC	, 
		 SCNDR_RQSTD_PHYSC_SPCLT_TYP_CODE                   as                   SCNDR_RQSTD_PHYSC_SPCLT_TYP_CODE	, 
		 SCNDR_RQSTD_PHYSC_SPCLT_TYP_DESC                   as                   SCNDR_RQSTD_PHYSC_SPCLT_TYP_DESC	, 
		 ADDENDUM_REQUEST_TYPE_CODE                         as                         ADDENDUM_REQUEST_TYPE_CODE	, 
		 ADDENDUM_REQUEST_TYPE_DESC                         as                         ADDENDUM_REQUEST_TYPE_DESC	, 
		 LANG_TYP_CD                                        as                                        LANG_TYP_CD	, 
		 LANG_TYP_NM                                        as                                        LANG_TYP_NM	, 
		 EXAM_RSCHDL_STS_RSN_CODE                           as                           EXAM_RSCHDL_STS_RSN_CODE	, 
		 EXAM_RSCHDL_STS_RSN_DESC                           as                           EXAM_RSCHDL_STS_RSN_DESC	, 
		 CASE_EXTRNL_NO                                     as                                     CASE_EXTRNL_NO	, 
		 RELATED_CASE_NO                                    as                                    RELATED_CASE_NO	, 
		 CDES_ADR_NO                                        as                                        CDES_ADR_NO	, 
		 REFERRED_TO                                        as                                        REFERRED_TO	, 
		 REFERRAL_DATE                                      as                                      REFERRAL_DATE	, 
		 REFERRAL_CREATE_DATE                               as                               REFERRAL_CREATE_DATE	, 
		 DUE_DATE                                           as                                           DUE_DATE	, 
		 ORG_UNT_NM                                         as                                         ORG_UNT_NM	, 
		 FNCT_ROLE_CD                                       as                                       FNCT_ROLE_CD	, 
		 CDES_CLMT_AVL_SUN_IND                              as                              CDES_CLMT_AVL_SUN_IND	, 
		 CDES_CLMT_AVL_MON_IND                              as                              CDES_CLMT_AVL_MON_IND	, 
		 CDES_CLMT_AVL_TUE_IND                              as                              CDES_CLMT_AVL_TUE_IND	, 
		 CDES_CLMT_AVL_WED_IND                              as                              CDES_CLMT_AVL_WED_IND	, 
		 CDES_CLMT_AVL_THU_IND                              as                              CDES_CLMT_AVL_THU_IND	, 
		 CDES_CLMT_AVL_FRI_IND                              as                              CDES_CLMT_AVL_FRI_IND	, 
		 CDES_CLMT_AVL_SAT_IND                              as                              CDES_CLMT_AVL_SAT_IND	, 
		 CDES_ITPRT_NEED_IND                                as                                CDES_ITPRT_NEED_IND	, 
		 CDES_GRTT_45_IND                                   as                                   CDES_GRTT_45_IND	, 
		 CDES_TRVL_REMB_IND                                 as                                 CDES_TRVL_REMB_IND	, 
		 CDES_ADDTNL_TST_IND                                as                                CDES_ADDTNL_TST_IND	, 
		 CDES_ADNDM_REQS_IND                                as                                CDES_ADNDM_REQS_IND	, 
		 CDES_RSLT_SUSPD_IND                                as                                CDES_RSLT_SUSPD_IND	, 
		 INJURED_WORK_EXAM_AVAILABILITY_NOTE                as                INJURED_WORK_EXAM_AVAILABILITY_NOTE	, 
		 EXAM_SCHDL_DTM                                     as                                     EXAM_SCHDL_DTM	, 
		 EXAM_SCHDL_DATE                                    as                                    EXAM_SCHDL_DATE	, 
		 EXAM_RESCHDL_COUNT                                 as                                 EXAM_RESCHDL_COUNT	, 
		 CRNT_CASE_STS_TYP_DESC                             as                             CRNT_CASE_STS_TYP_DESC	, 
		 CRNT_CASE_STS_RSN_TYP_DESC                         as                         CRNT_CASE_STS_RSN_TYP_DESC	, 
		 EXAM_DATE                                          as                                          EXAM_DATE	, 
		 PRVDR_PEACH_NUMBER                                 as                                 PRVDR_PEACH_NUMBER	, 
		 EXAM_LOC_STR1                                      as                                      EXAM_LOC_STR1	, 
		 EXAM_LOC_STR2                                      as                                      EXAM_LOC_STR2	, 
		 EXAM_LCTN_CITY                                     as                                     EXAM_LCTN_CITY	, 
		 EXAM_LCTN_STATE_NAME                               as                               EXAM_LCTN_STATE_NAME	, 
		 EXAM_LCTN_ZIP                                      as                                      EXAM_LCTN_ZIP	, 
		 EXAM_LCTN_COUNTY_NAME                              as                              EXAM_LCTN_COUNTY_NAME	, 
		 EXAM_LCTN_COUNTRY_NAME                             as                             EXAM_LCTN_COUNTRY_NAME	, 
		 OUT_OF_STATE_IND                                   as                                   OUT_OF_STATE_IND	, 
		 ZIP_CODE_LONGITUDE                                 as                                 ZIP_CODE_LONGITUDE	, 
		 ZIP_CODE_LATITUDE                                  as                                  ZIP_CODE_LATITUDE	, 
		 EXAM_SCHDL_USER_LGN_NM                             as                             EXAM_SCHDL_USER_LGN_NM	, 
		 NO_SHOW_IND                                        as                                        NO_SHOW_IND	, 
		 EXAM_RESCHDL_IND                                   as                                   EXAM_RESCHDL_IND	, 
		 NO_SHOW_COUNT                                      as                                      NO_SHOW_COUNT	, 
		 EXAM_REPORT_RECV_DATE                              as                              EXAM_REPORT_RECV_DATE	, 
		 CASE_RSOL_TYP_NM                                   as                                   CASE_RSOL_TYP_NM	, 
		 CASE_COMP_DT                                       as                                       CASE_COMP_DT	, 
		 CURRENT_IND                                        as                                        CURRENT_IND
	 from SRC_CES )


---- RENAME LAYER ----


, RENAME_CES as ( SELECT  
		 SCHEDULE_NUMBER                                    as                                    SCHEDULE_NUMBER , 
		 CASE_ID                                            as                                            CASE_ID , 
		 CASE_NO                                            as                                        CASE_NUMBER , 
		 CLM_NO                                             as                                       CLAIM_NUMBER , 
		 CLM_AGRE_ID                                        as                                        CLM_AGRE_ID , 
		 CASE_OWNER                                         as                                         CASE_OWNER , 
		 CASE_OWNER_LGN_NM                                  as                                  CASE_OWNER_LGN_NM , 
		 CASE_OWNER_FUNCTIONAL_ROLE                         as                         CASE_OWNER_FUNCTIONAL_ROLE , 
		 CASE_NM                                            as                                            CASE_NM , 
		 CASE_INITIATED_DATE                                as                               CASE_INITIATION_DATE , 
		 CASE_EFFECTIVE_DATE                                as                                CASE_EFFECTIVE_DATE , 
		 CASE_DUE_DATE                                      as                                      CASE_DUE_DATE , 
		 CASE_TYP_CD                                        as                                     CASE_TYPE_CODE , 
		 CASE_TYP_NM                                        as                                     CASE_TYPE_DESC , 
		 CASE_CTG_TYP_CD                                    as                                 CASE_CATEGORY_CODE , 
		 CASE_CTG_TYP_NM                                    as                                 CASE_CATEGORY_DESC , 
		 APP_CNTX_TYP_CD                                    as                                  CONTEXT_TYPE_CODE , 
		 APP_CNTX_TYP_NM                                    as                                  CONTEXT_TYPE_DESC , 
		 CASE_PRTY_TYP_CD                                   as                                 CASE_PRIORITY_CODE , 
		 CASE_PRTY_TYP_NM                                   as                                 CASE_PRIORITY_DESC , 
		 CASE_RSOL_TYP_CD                                   as                                  CASE_RESOLVE_CODE , 
		 CASE_RSOL_TYP_NM                                   as                                  CASE_RESOLVE_DESC , 
		 EXAM_TYPE_CD                                       as                                     EXAM_TYPE_CODE , 
		 EXAM_TYPE_DESC                                     as                                     EXAM_TYPE_NAME , 
		 CASE_PRFL_CTG_TYP_CD                               as                         CASE_PROFILE_CATEGORY_CODE , 
		 CASE_PRFL_CTG_TYP_NM                               as                         CASE_PROFILE_CATEGORY_DESC , 
		 CASE_STT_TYP_CD                                    as                                    CASE_STATE_CODE , 
		 CASE_STT_TYP_NM                                    as                                    CASE_STATE_DESC , 
		 CASE_STS_TYP_CD                                    as                                   CASE_STATUS_CODE , 
		 CASE_STS_TYP_NM                                    as                                   CASE_STATUS_DESC , 
		 CASE_STS_RSN_TYP_CD                                as                      CASE_STATE_STATUS_REASON_CODE , 
		 CASE_STS_RSN_TYP_NM                                as                      CASE_STATE_STATUS_REASON_DESC , 
		 EXAM_REQUESTOR_TYP_CD                              as                           EXAM_REQUESTOR_TYPE_CODE , 
		 EXAM_REQUESTOR_TYP_DESC                            as                           EXAM_REQUESTOR_TYPE_DESC , 
		 RQSTD_PHYSC_SPCLT_TYP_CODE                         as                    PHYSICIAN_SPECIALTY_NEEDED_CODE , 
		 RQSTD_PHYSC_SPCLT_TYP_DESC                         as                    PHYSICIAN_SPECIALTY_NEEDED_DESC , 
		 SCNDR_RQSTD_PHYSC_SPCLT_TYP_CODE                   as             SECOND_CHOICE_PHYSICIAN_SPECIALTY_CODE , 
		 SCNDR_RQSTD_PHYSC_SPCLT_TYP_DESC                   as             SECOND_CHOICE_PHYSICIAN_SPECIALTY_DESC , 
		 ADDENDUM_REQUEST_TYPE_CODE                         as                         ADDENDUM_REQUEST_TYPE_CODE , 
		 ADDENDUM_REQUEST_TYPE_DESC                         as                         ADDENDUM_REQUEST_TYPE_DESC , 
		 LANG_TYP_CD                                        as                                 LANGUAGE_TYPE_CODE , 
		 LANG_TYP_NM                                        as                                 LANGUAGE_TYPE_DESC , 
		 EXAM_RSCHDL_STS_RSN_CODE                           as                 EXAM_RESCHEDULE_STATUS_REASON_CODE , 
		 EXAM_RSCHDL_STS_RSN_DESC                           as                 EXAM_RESCHEDULE_STATUS_REASON_DESC , 
		 CASE_EXTRNL_NO                                     as                               CASE_EXTERNAL_NUMBER , 
		 RELATED_CASE_NO                                    as                                RELATED_CASE_NUMBER , 
		 CDES_ADR_NO                                        as                                        CDES_ADR_NO , 
		 REFERRED_TO                                        as                                        REFERRED_TO , 
		 REFERRAL_DATE                                      as                                 EXAM_REFERRAL_DATE , 
		 REFERRAL_CREATE_DATE                               as                               REFERRAL_CREATE_DATE , 
		 DUE_DATE                                           as                                           DUE_DATE , 
		 ORG_UNT_NM                                         as                           ORGANIZATIONAL_UNIT_NAME , 
		 FNCT_ROLE_CD                                       as                          USER_FUNCTIONAL_ROLE_CODE , 
		 CDES_CLMT_AVL_SUN_IND                              as                            SUNDAY_AVAILABILITY_IND , 
		 CDES_CLMT_AVL_MON_IND                              as                            MONDAY_AVAILABILITY_IND , 
		 CDES_CLMT_AVL_TUE_IND                              as                           TUESDAY_AVAILABILITY_IND , 
		 CDES_CLMT_AVL_WED_IND                              as                         WEDNESDAY_AVAILABILITY_IND , 
		 CDES_CLMT_AVL_THU_IND                              as                          THURSDAY_AVAILABILITY_IND , 
		 CDES_CLMT_AVL_FRI_IND                              as                            FRIDAY_AVAILABILITY_IND , 
		 CDES_CLMT_AVL_SAT_IND                              as                          SATURDAY_AVAILABILITY_IND , 
		 CDES_ITPRT_NEED_IND                                as                             INTERPRETER_NEEDED_IND , 
		 CDES_GRTT_45_IND                                   as                          GREATER_THAN_45_MILES_IND , 
		 CDES_TRVL_REMB_IND                                 as                           TRAVEL_REIMBURSEMENT_IND , 
		 CDES_ADDTNL_TST_IND                                as                             ADDITIONAL_TESTING_IND , 
		 CDES_ADNDM_REQS_IND                                as                             ADDENDUM_REQUESTED_IND , 
		 CDES_RSLT_SUSPD_IND                                as                               RESULT_SUSPENDED_IND , 
		 INJURED_WORK_EXAM_AVAILABILITY_NOTE                as                   AVAILABILITY_SPECIAL_REQUIREMENT , 
		 EXAM_SCHDL_DTM                                     as                             EXAM_SCHEDULE_DATETIME , 
		 EXAM_SCHDL_DATE                                    as                                 EXAM_SCHEDULE_DATE , 
		 EXAM_RESCHDL_COUNT                                 as                                 EXAM_RESCHDL_COUNT , 
		 CRNT_CASE_STS_TYP_DESC                             as                             CRNT_CASE_STS_TYP_DESC , 
		 CRNT_CASE_STS_RSN_TYP_DESC                         as                         CRNT_CASE_STS_RSN_TYP_DESC , 
		 EXAM_DATE                                          as                                          EXAM_DATE , 
		 PRVDR_PEACH_NUMBER                                 as                                 PRVDR_PEACH_NUMBER , 
		 EXAM_LOC_STR1                                      as                                  LOCATION_STRING_1 , 
		 EXAM_LOC_STR2                                      as                                  LOCATION_STRING_2 , 
		 EXAM_LCTN_CITY                                     as                                      LOCATION_CITY , 
		 EXAM_LCTN_STATE_NAME                               as                                     LOCATION_STATE , 
		 EXAM_LCTN_ZIP                                      as                                  LOCATION_ZIP_CODE , 
		 EXAM_LCTN_COUNTY_NAME                              as                                    LOCATION_COUNTY , 
		 EXAM_LCTN_COUNTRY_NAME                             as                                   LOCATION_COUNTRY , 
		 OUT_OF_STATE_IND                                   as                                   OUT_OF_STATE_IND , 
		 ZIP_CODE_LONGITUDE                                 as                                 ZIP_CODE_LONGITUDE , 
		 ZIP_CODE_LATITUDE                                  as                                  ZIP_CODE_LATITUDE , 
		 EXAM_SCHDL_USER_LGN_NM                             as                             EXAM_SCHDL_USER_LGN_NM , 
		 NO_SHOW_IND                                        as                                        NO_SHOW_IND , 
		 EXAM_RESCHDL_IND                                   as                                     RESCHEDULE_IND , 
		 NO_SHOW_COUNT                                      as                                      NO_SHOW_COUNT , 
		 EXAM_REPORT_RECV_DATE                              as                          EXAM_REPORT_RECEIVED_DATE , 
		 CASE_RSOL_TYP_NM                                   as                          CASE_RESOLUTION_TYPE_DESC , 
		 CASE_COMP_DT                                       as                                 CASE_COMPLETE_DATE , 
		 CURRENT_IND                                        as                          CURRENT_EXAM_SCHEDULE_IND 
		FROM LOGIC_CES
            )

---- FILTER LAYER ----

FILTER_CES                            as ( SELECT * FROM    RENAME_CES    )

---- JOIN LAYER ----

 JOIN_CES         as  ( SELECT * 
				FROM  FILTER_CES )
 SELECT * FROM  JOIN_CES