create DATABASE IDENTIFIER('"YIPIT_DATASHARE"') FROM SHARE IDENTIFIER('FDDKJIL.USEAST2AZUREYIPITDATA."YIPITDATA_DELIVERY_PALETURQUOISEBROOK_SHARE"');

GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATALOAD_DEV"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATALOAD_QA"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATALOAD_PROD"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATALOAD_RO"');

GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATAREAD_DEV"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATAREAD_QA"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATAREAD_PROD"');

GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DV_RAW_VAULT_RW"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DV_RAW_VAULT_RO"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATAMOVE"');
GRANT IMPORTED PRIVILEGES ON DATABASE IDENTIFIER('"YIPIT_DATASHARE"') TO ROLE IDENTIFIER('"DATALOAD"');

-- Test validation
select *
from YIPIT_DATASHARE.YIPITDATA.YIPIT_GENERAL_DISCLAIMER_VIEW;
