
  CREATE TABLE "AR"."RA_CUST_TRX_LINE_SALESREPS_ALL" 
   (	"CUST_TRX_LINE_SALESREP_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CUSTOMER_TRX_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"SALESREP_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CUSTOMER_TRX_LINE_ID" NUMBER(15,0), 
	"REVENUE_AMOUNT_SPLIT" NUMBER, 
	"NON_REVENUE_AMOUNT_SPLIT" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"REQUEST_ID" NUMBER(15,0), 
	"PROGRAM_APPLICATION_ID" NUMBER(15,0), 
	"PROGRAM_ID" NUMBER(15,0), 
	"PROGRAM_UPDATE_DATE" DATE, 
	"NON_REVENUE_PERCENT_SPLIT" NUMBER, 
	"REVENUE_PERCENT_SPLIT" NUMBER, 
	"ORIGINAL_LINE_SALESREP_ID" NUMBER(15,0), 
	"PREV_CUST_TRX_LINE_SALESREP_ID" NUMBER(15,0), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ORG_ID" NUMBER(15,0) DEFAULT NULL, 
	"WH_UPDATE_DATE" DATE, 
	"REVENUE_ADJUSTMENT_ID" NUMBER(15,0), 
	"REVENUE_SALESGROUP_ID" NUMBER, 
	"NON_REVENUE_SALESGROUP_ID" NUMBER, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 5 PCTUSED 60 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 251658240 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 