
  CREATE TABLE "ONT"."OE_TRANSACTION_TYPES_TL" 
   (	"TRANSACTION_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(4) NOT NULL ENABLE, 
	"SOURCE_LANG" VARCHAR2(4) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000), 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"PROGRAM_APPLICATION_ID" NUMBER, 
	"PROGRAM_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 983040 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 4
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_SEED" 